### ISSUE TITLE
Photo Server link

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/OneLifeWeb#3]
This is driving me nuts. I need to fix it later.

I moved $photoServerURL from lineageServer/settings.php to config.php

lineageServer/server.php imports settings.php which imports config.php

In config.php, $photoServerURL is now made with string concatenation to avoid setting the main URL in more than one location. Lineage server absolutely will not have this and fails to use the link properly. But if you set the full URL as one string in linageServer/settings.php, no worries. Grr.

**Comment by Strohtaler** [comment]
I noted in most all `settings.php` and in `config.php` that string concatenation is being done using `+` (plus) operator - in PHP this is only from addition (numbers), string concatenation is done using `.` (decimal point) !

**Comment by connorhsm** [comment]
Thank you! Something silly I should have checked!
